name: NotQuiteModded
version: '${project.version}'
main: me.playfulpotato.notquitemodded.NotQuiteModded
description: A library plugin made to help other plugins with content creation.
api-version: '1.20'
load: STARTUP